using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.BodyTakeover;

[GenerateTypedNameReferences]
public sealed partial class BodyTakeoverTransferWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public BodyTakeoverTransferWindow(string entityName, TimeSpan transferDelay, Action onNow, Action onWait, Action onDecline)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var delayText = transferDelay.TotalMinutes >= 1
            ? _loc.GetString("body-takeover-delay-minutes", ("count", (int)Math.Round(transferDelay.TotalMinutes)))
            : _loc.GetString("body-takeover-delay-seconds", ("count", (int)Math.Round(transferDelay.TotalSeconds)));

        BodyLabel.Text = _loc.GetString("body-takeover-transfer-window-body",
            ("entity", entityName),
            ("delay", delayText));
        TransferNowButton.Text = _loc.GetString("body-takeover-transfer-window-now");
        WaitButton.Text = _loc.GetString("body-takeover-transfer-window-wait");
        DeclineButton.Text = _loc.GetString("body-takeover-transfer-window-decline");

        TransferNowButton.OnPressed += _ => onNow();
        WaitButton.OnPressed += _ => onWait();
        DeclineButton.OnPressed += _ => onDecline();
    }
}
