using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Scp.BodyTakeover;

[GenerateTypedNameReferences]
public sealed partial class BodyTakeoverPollWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public BodyTakeoverPollWindow(string entityName, Action onAccept, Action onDecline)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        BodyLabel.Text = _loc.GetString("body-takeover-poll-window-body", ("entity", entityName));
        AcceptButton.Text = _loc.GetString("body-takeover-poll-window-accept");
        DeclineButton.Text = _loc.GetString("body-takeover-poll-window-decline");

        AcceptButton.OnPressed += _ => onAccept();
        DeclineButton.OnPressed += _ => onDecline();

        DeclineButton.GrabKeyboardFocus();
    }
}
