using Content.Client.Stylesheets;
using Content.Shared._Scp.SafeTime;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Scp.SafeTime;

[GenerateTypedNameReferences]
public sealed partial class SafeTimeProgressBar : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private static readonly StyleBoxFlat SafeTimeColor = new()
    {
        BackgroundColor = StyleNano.ConcerningOrangeFore,
    };

    public SafeTimeProgressBar()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Обновляет и актуализирует информацию о безопасном времени
    /// </summary>
    /// <param name="timeEnd">Абсолютное время окончания safe time.</param>
    /// <param name="totalTime">Полная длительность safe time для расчета прогресса.</param>
    public void UpdateSafeTimeInfo(TimeSpan? timeEnd, TimeSpan totalTime)
    {
        if (!timeEnd.HasValue || totalTime <= TimeSpan.Zero)
        {
            Visible = false;
            return;
        }

        var timeLeft = timeEnd.Value - _timing.CurTime;
        if (timeLeft <= TimeSpan.Zero)
        {
            Visible = false;
            return;
        }

        Visible = true;

        var timeLeftString = SafeTimeSystem.GetTimeLeft(timeLeft);
        InfoLabel.Text = _loc.GetString("safe-time-title", ("time", timeLeftString));

        var totalSeconds = (int) totalTime.TotalSeconds;
        ProgressBar.MaxValue = totalSeconds;
        ProgressBar.ForegroundStyleBoxOverride = SafeTimeColor;

        var elapsed = Math.Clamp(totalSeconds - (int) timeLeft.TotalSeconds, 0, totalSeconds);
        ProgressBar.Value = elapsed;
        ProgressLabel.Text = $"{(int) (elapsed / (float) totalSeconds * 100)}%";
    }
}
