- type: job
  id: FondSeniorSecurityOfficer
  name: ghost-role-information-fond-senior-security-officer-name
  description: ghost-role-information-fond-senior-security-officer-description
  playTimeTracker: JobFondSeniorSecurityOfficer
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 #5 hrs
  setPreference: false
  startingGear: FondSeniorSecurityOfficerGear
  icon: JobFondSeniorSecurityOfficer
  supervisors: ghost-role-information-fond-senior-security-officer-supervisors
  canBeAntag: false
  radioBold: true
  weight: 820
  overrideConsoleVisibility: false
  alwaysShowInBanPanel: true
  accessGroups:
  - FondSecurity
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: FondSeniorSecurityOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: MtfTacticalBackpack
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatBeretSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBulletproof
    neck: ClothingNeckCloakWhite
    belt: ScpClothingBeltSecurityWebbingFilled
    id: KeyCardFondSeniorSecurityOfficer
    ears: ClothingHeadsetAltMTF
    pocket1: PinpointerUniversal
  storage:
    belt:
    - FlashlightSeclite
    - WeaponTaser
    - GrenadeStinger

- type: startingGear
  id: FondSeniorSecurityOfficerGearAltA
  parent: FondSeniorSecurityOfficerGear
  equipment:
    suitstorage: WeaponSubMachineGunMP5
    pocket2: PouchAmmo
  storage:
    back:
    - Crowbar
    - MagazineMP5
    - MagazineMP5
    - MagazineMP5
    - MagazineMP5
    - Gauze
    - ScpRadioHandheldSecurity
    - BoxSurvivalSecurity
    - HandheldCrewMonitor

- type: startingGear
  id: FondSeniorSecurityOfficerGearAltB
  parent: FondSeniorSecurityOfficerGear
  equipment:
    suitstorage: WeaponShotgunSPAS12
    pocket2: HandheldCrewMonitor
  storage:
    back:
    - Crowbar
    - BoxLethalshot
    - BoxLethalshot
    - BoxLethalshot
    - Gauze
    - BoxSurvivalSecurity
    - ScpRadioHandheldSecurity
